-- SQL para criar a tabela de comentários

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES cards(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Políticas de acesso (RLS) para comments

ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 1. Quem pode VER comentários? (Membros da organização dona do board do card)
CREATE POLICY "Org members can view comments" ON comments
  FOR SELECT USING (
    card_id IN (
      SELECT id FROM cards WHERE list_id IN (
        SELECT id FROM lists WHERE board_id IN (
          SELECT id FROM boards WHERE organization_id IN (
            SELECT organization_id FROM organization_members 
            WHERE user_id = auth.uid()
          )
        )
      )
    )
  );

-- 2. Quem pode CRIAR comentários? (Membros da organização)
CREATE POLICY "Members can create comments" ON comments
  FOR INSERT WITH CHECK (
    auth.uid() = user_id AND -- Garante que user_id é do próprio usuário
    card_id IN (
      SELECT id FROM cards WHERE list_id IN (
        SELECT id FROM lists WHERE board_id IN (
          SELECT id FROM boards WHERE organization_id IN (
            SELECT organization_id FROM organization_members 
            WHERE user_id = auth.uid() AND role IN ('owner', 'admin', 'member')
          )
        )
      )
    )
  );

-- 3. Quem pode DELETAR comentários? (O dono do comentário ou Admin da Org)
CREATE POLICY "Users can delete own comments or Admins" ON comments
  FOR DELETE USING (
    (auth.uid() = user_id) OR -- É dono do comentário
    (
       card_id IN (
        SELECT id FROM cards WHERE list_id IN (
          SELECT id FROM lists WHERE board_id IN (
            SELECT id FROM boards WHERE organization_id IN (
              SELECT organization_id FROM organization_members 
              WHERE user_id = auth.uid() AND role IN ('owner', 'admin') -- Admin da Org
            )
          )
        )
      )
    )
  );
