name: CI SyncFlow (Angular)

#Roda quando der push ou pull request para a branch master
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    #Baixa o código do repositório
    - name: Checkout do código
      uses: actions/checkout@v4

    #Prepara o Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    #Instala dependências
    - name: Instalar Dependências
      run: npm ci

    #Verifica se o código compila
    - name: Verificar Build (Produção)
      run: npm run build -- --configuration production
      
    # Futuramente 'npm run test' aqui. 
